export const editorCopy = {
  en: {
    title: 'Edit your subtitles', intro: 'Review each line, then burn the translation into your video.',
    loading: 'Loading subtitles…', loadError: 'Could not load this session. Please try again or upload the video again.',
    retry: 'Retry', reset: 'Upload another video', subtitle: 'Subtitle', seek: 'Seek to',
    previewError: 'Your browser cannot preview this video. You can still edit subtitles and render it.',
    apply: 'Apply translation', again: 'Render again', connecting: 'Waiting for rendering status…',
    queued: 'Position in queue', burn: 'Burning subtitles…', done: 'Your video is ready.',
    failed: 'Rendering failed. Your edits are still here; please try again.',
    disconnected: 'Connection lost. The render may have been cancelled. Your edits are still here; please try again.',
    invalid: 'Each subtitle needs text. Use single line breaks within a subtitle, without blank lines.',
    video: 'Download video', srt: 'Download edited SRT', keepOpen: 'Keep this page open while rendering. Leaving cancels a queued or running render.',
    local: 'Text edits are saved to the server when you apply the translation. Download SRT to keep a local copy.',
    support: 'Support this service', noJs: 'JavaScript is needed to edit subtitles.',
  },
  uk: {
    title: 'Редагуйте субтитри', intro: 'Перевірте кожен рядок, а потім вшийте переклад у відео.',
    loading: 'Завантаження субтитрів…', loadError: 'Не вдалося завантажити сесію. Спробуйте ще раз або завантажте відео знову.',
    retry: 'Спробувати ще раз', reset: 'Завантажити інше відео', subtitle: 'Субтитр', seek: 'Перейти до',
    previewError: 'Браузер не може відтворити це відео. Ви можете редагувати субтитри та вшити їх у відео.',
    apply: 'Застосувати переклад', again: 'Обробити знову', connecting: 'Очікуємо статус обробки…',
    queued: 'Позиція в черзі', burn: 'Вшиваємо субтитри…', done: 'Ваше відео готове.',
    failed: 'Помилка обробки. Ваші зміни залишилися тут; спробуйте ще раз.',
    disconnected: 'З’єднання втрачено. Обробку могло бути скасовано. Ваші зміни залишилися тут; спробуйте ще раз.',
    invalid: 'Кожен субтитр має містити текст. Використовуйте переноси рядків без порожніх рядків.',
    video: 'Завантажити відео', srt: 'Завантажити змінений SRT', keepOpen: 'Не закривайте сторінку під час обробки. Перехід скасовує завдання в черзі або під час обробки.',
    local: 'Зміни зберігаються на сервері після застосування перекладу. Завантажте SRT, щоб зберегти локальну копію.',
    support: 'Підтримати сервіс', noJs: 'Для редагування субтитрів потрібен JavaScript.',
  },
};
