export const uploadCopy = {
  en: {
    title: 'Create English subtitles', intro: 'Upload your video, then review the translated subtitles beside the player.',
    loading: 'Loading upload options…', optionsError: 'Could not load upload options.', retry: 'Retry', file: 'Video file',
    drop: 'Drop one video here or choose a file', language: 'Language spoken in the video', model: 'Whisper model',
    modelHint: 'Larger models can be more accurate but take longer to process.', upload: 'Upload and generate subtitles',
    fileError: 'Choose one non-empty video in an allowed format.', sizeError: 'The video exceeds the size limit.',
    limits: 'Limits', minutes: 'minutes', source: 'The language above is the source language. Subtitles are generated in English.',
    license: 'License', key: 'License key', activate: 'Activate', activating: 'Activating…', active: 'License active — unlimited translations',
    remaining: 'Free translations remaining today', licenseError: 'Could not check your license or quota.', activated: 'License activated.',
    invalidKey: 'Enter a license key.', uploading: 'Uploading video', queued: 'Position in queue', connecting: 'Waiting for processing status…',
    compress: 'Compressing video', transcribe: 'Generating English subtitles', ready: 'Opening the subtitle editor…',
    keepOpen: 'Keep this page open. Leaving it cancels a queued or running task.',
    networkError: 'Connection lost. Please try again.', processingError: 'Processing failed. Please try again.',
    quotaError: 'Daily limit reached. Activate a license or try again tomorrow.', uploadError: 'Upload failed.',
    connectionError: 'Connection to the worker was lost. The task may have been cancelled; please try again.',
    contact: 'Get a license via Telegram', notice: 'Your video language and model choices are saved in preference cookies.',
    privacy: 'Privacy policy', noJs: 'JavaScript is needed to upload a video and receive processing status.',
  },
  uk: {
    title: 'Створіть англійські субтитри', intro: 'Завантажте відео, а потім перевірте перекладені субтитри поруч із плеєром.',
    loading: 'Завантаження налаштувань…', optionsError: 'Не вдалося завантажити налаштування.', retry: 'Спробувати ще раз', file: 'Відеофайл',
    drop: 'Перетягніть одне відео сюди або оберіть файл', language: 'Мова, якою говорять у відео', model: 'Модель Whisper',
    modelHint: 'Більші моделі можуть бути точнішими, але обробка триває довше.', upload: 'Завантажити й створити субтитри',
    fileError: 'Оберіть одне непорожнє відео дозволеного формату.', sizeError: 'Відео перевищує обмеження розміру.',
    limits: 'Обмеження', minutes: 'хвилин', source: 'Вище обрано мову оригіналу. Субтитри створюються англійською.',
    license: 'Ліцензія', key: 'Ліцензійний ключ', activate: 'Активувати', activating: 'Активація…', active: 'Ліцензія активна — переклади без обмежень',
    remaining: 'Залишилося безкоштовних перекладів на сьогодні', licenseError: 'Не вдалося перевірити ліцензію або ліміт.', activated: 'Ліцензію активовано.',
    invalidKey: 'Введіть ліцензійний ключ.', uploading: 'Завантаження відео', queued: 'Позиція в черзі', connecting: 'Очікуємо статус обробки…',
    compress: 'Стискання відео', transcribe: 'Створення англійських субтитрів', ready: 'Відкриваємо редактор субтитрів…',
    keepOpen: 'Не закривайте цю сторінку. Перехід з неї скасовує завдання в черзі або під час обробки.',
    networkError: 'З’єднання втрачено. Спробуйте ще раз.', processingError: 'Помилка обробки. Спробуйте ще раз.',
    quotaError: 'Денний ліміт вичерпано. Активуйте ліцензію або спробуйте завтра.', uploadError: 'Не вдалося завантажити відео.',
    connectionError: 'З’єднання з обробником втрачено. Завдання могло бути скасоване; спробуйте ще раз.',
    contact: 'Отримати ліцензію через Telegram', notice: 'Обрана мова відео та модель зберігаються у файлах cookie.',
    privacy: 'Політика конфіденційності', noJs: 'Для завантаження відео та отримання статусу потрібен JavaScript.',
  },
};
